# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [8]:
# read_csv

city_weather_df = pd.read_csv("city_weather_data.csv")

city_weather_df

city_weather_df.drop(columns=['Unnamed: 0'])

,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,victoria,22.2855,114.1577,81.07,90,67,7.00,HK,1634144316
1,bereda,43.2686,-7.5406,65.88,72,1,4.63,ES,1634144452
2,brae,60.3964,-1.3530,53.51,85,100,23.26,GB,1634144452
3,pundaguitan,6.3711,126.1689,83.80,76,100,13.44,PH,1634144453
4,grindavik,63.8424,-22.4338,41.47,75,75,19.57,IS,1634144453
...,...,...,...,...,...,...,...,...,...
559,ancud,-41.8697,-73.8203,51.33,92,100,23.64,CL,1634144664
560,port blair,11.6667,92.7500,81.09,86,100,13.42,IN,1634144665
561,chato,-2.6378,31.7669,72.79,67,14,5.55,TZ,1634144665
562,birao,10.2849,22.7882,75.51,79,96,3.94,CF,1634144666
563,hazorasp,41.3194,61.0742,48.04,22,0,10.02,UZ,1634144666

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [ ]:
# Use .loc 

# Caveat: make sure your ideal isn't too ideal,
# meaning check the length of the resulting dataframe so it has rows

# Take the cleaned df and title it hotel_df

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
hotel_df['Hotel Name'] = ""
hotel_df['address'] = ""
hotel_df['price_level'] = ""
hotel_df['rating'] = ""

types_df.head()

In [ ]:
# find the closest restaurant of each type to coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gkey,
}


# use iterrows to iterate through pandas dataframe
for index, row in types_df.iterrows():

    # get type from df
    
    lat = row['Latitude']
    lon = riw['Longitude']

    # add keyword to params dict
    params['location'] = f'{lat},{lon}'

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {'City}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest {restr_type} restaurant is {results[0]['name']}.")
        
        types_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map

# gmaps marker layer with the locations from hotel_df

locations = hotel_df[['Latitude','Longitude']]

# going to have a gmaps.marker_layer using locations, info_box_content=hotel_info

# Display figure